### ISSUE TITLE
Should 'WARNING: record?...' just be ignored?

### ISSUE THREAD

**Issue by GHExplorer** [clojure-numerics/expresso#11]
Hi,

When loading expresso, I get these warnings:

Program started.
Hi there
WARNING: record? already refers to: #'clojure.core/record? in namespace: clojure.core.logic, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.properties, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.impl.pimplementation, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.types, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.impl.matcher, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.utils, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: clojure.core.logic.fd, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: clojure.core.logic.unifier, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.construct, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.impl.polynomial, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.rules, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.simplify, being replaced by: #'clojure.core.logic/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: numeric.expresso.optimize, being replaced by: #'clojure.core.logic/record?

According to posts about similar messages in other contexts & libraries, this should just be ignored.  Is that correct?

**Comment by mikera** [comment]
I think you can safely ignore.

**Comment by mschuene** [comment]
There was an issue with core.logic and clojure.core in 1.6 both having a record? function.
I updated the dependencies and removed the warnings
could you please check out whether the warnings are removed for you with the latest snapshot release?

**Comment by GHExplorer** [comment]
Yep, completely gone.  Everything's good, thanks.
