### ISSUE TITLE
Can Clojars be updated with the latest build?

### ISSUE THREAD

**Issue by GHExplorer** [clojure-numerics/expresso#12]
Hi,

Regarding the warnings the other day, I tested that they were gone, by building the standalone jar, and calling some routines externally from java.

But clojars doesn't seem to be updated, with the fixes.

**Comment by mschuene** [comment]
hmm clojars reports that is has been updated:
https://clojars.org/expresso/versions/0.2.1-SNAPSHOT

do you have offline? true in your project.clj or do you use a different snapshot version?

**Comment by GHExplorer** [comment]
It's because I used 

[expresso "0.2.1"]


instead of 

[expresso "0.2.1-SNAPSHOT"]

It almost compiles now, but there's a different error.  However, I'm pretty sure it's my problem, I'll play with it, the next couple of days:


Exception in thread "main" java.lang.NoSuchMethodError: clojure.core.logic.LVar.<init>(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V

**Comment by mschuene** [comment]
No problem, report when you get errors you think come from expresso
