### ISSUE TITLE
Crash on import

### ISSUE THREAD

**Issue by oneiromantica** [clojure-numerics/expresso#35]
## How to reproduce

`(require '[numeric.expresso.core])`

## Observed

Throws with stack trace due to `mat/abs` not found

## Expected

Imports successfully

## Version

`expresso/expresso` 0.2.2

## Suggested solution

Update `net.mikera/core.matrix` dependency to version 0.6.3

**Comment by mschuene** [comment]
I updated the core.matrx dependency and deployed a new version 0.2.4 to clojars
This should resolve the issue.
